// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event_Payload_CustomField_FieldType int32

const (
	Event_Payload_CustomField_STRING  Event_Payload_CustomField_FieldType = 0
	Event_Payload_CustomField_NUMBER  Event_Payload_CustomField_FieldType = 1
	Event_Payload_CustomField_BOOLEAN Event_Payload_CustomField_FieldType = 2
	Event_Payload_CustomField_JSON    Event_Payload_CustomField_FieldType = 3
	Event_Payload_CustomField_BINARY  Event_Payload_CustomField_FieldType = 4
)

// Enum value maps for Event_Payload_CustomField_FieldType.
var (
	Event_Payload_CustomField_FieldType_name = map[int32]string{
		0: "STRING",
		1: "NUMBER",
		2: "BOOLEAN",
		3: "JSON",
		4: "BINARY",
	}
	Event_Payload_CustomField_FieldType_value = map[string]int32{
		"STRING":  0,
		"NUMBER":  1,
		"BOOLEAN": 2,
		"JSON":    3,
		"BINARY":  4,
	}
)

func (x Event_Payload_CustomField_FieldType) Enum() *Event_Payload_CustomField_FieldType {
	p := new(Event_Payload_CustomField_FieldType)
	*p = x
	return p
}

func (x Event_Payload_CustomField_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Payload_CustomField_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (Event_Payload_CustomField_FieldType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x Event_Payload_CustomField_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Payload_CustomField_FieldType.Descriptor instead.
func (Event_Payload_CustomField_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 3, 1, 0}
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventTimestamp int64                  `protobuf:"varint,2,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	User           *Event_UserContext     `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	Session        *Event_SessionContext  `protobuf:"bytes,11,opt,name=session,proto3" json:"session,omitempty"`
	Tracing        *Event_TracingContext  `protobuf:"bytes,12,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Payload        *Event_Payload         `protobuf:"bytes,20,opt,name=payload,proto3" json:"payload,omitempty"`
	Enrichment     *Event_Enrichment      `protobuf:"bytes,21,opt,name=enrichment,proto3" json:"enrichment,omitempty"`
	Metrics        []*Event_Metric        `protobuf:"bytes,30,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Tags           []*Event_Tag           `protobuf:"bytes,31,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Event) GetEventTimestamp() int64 {
	if x != nil {
		return x.EventTimestamp
	}
	return 0
}

func (x *Event) GetUser() *Event_UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Event) GetSession() *Event_SessionContext {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Event) GetTracing() *Event_TracingContext {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Event) GetPayload() *Event_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetEnrichment() *Event_Enrichment {
	if x != nil {
		return x.Enrichment
	}
	return nil
}

func (x *Event) GetMetrics() []*Event_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Event) GetTags() []*Event_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Event_UserContext struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserId        string                     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                     `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId      string                     `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IpAddress     string                     `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                     `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Attributes    map[string]string          `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Profile       *Event_UserContext_Profile `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_UserContext) Reset() {
	*x = Event_UserContext{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UserContext) ProtoMessage() {}

func (x *Event_UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UserContext.ProtoReflect.Descriptor instead.
func (*Event_UserContext) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_UserContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event_UserContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event_UserContext) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Event_UserContext) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Event_UserContext) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Event_UserContext) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Event_UserContext) GetProfile() *Event_UserContext_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type Event_SessionContext struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	SessionId     string                           `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartedAt     int64                            `protobuf:"varint,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastActivity  int64                            `protobuf:"varint,3,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	EntryUrl      string                           `protobuf:"bytes,4,opt,name=entry_url,json=entryUrl,proto3" json:"entry_url,omitempty"`
	Referrers     []string                         `protobuf:"bytes,5,rep,name=referrers,proto3" json:"referrers,omitempty"`
	SessionData   map[string]string                `protobuf:"bytes,6,rep,name=session_data,json=sessionData,proto3" json:"session_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Navigation    *Event_SessionContext_Navigation `protobuf:"bytes,10,opt,name=navigation,proto3" json:"navigation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_SessionContext) Reset() {
	*x = Event_SessionContext{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_SessionContext) ProtoMessage() {}

func (x *Event_SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_SessionContext.ProtoReflect.Descriptor instead.
func (*Event_SessionContext) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Event_SessionContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event_SessionContext) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Event_SessionContext) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *Event_SessionContext) GetEntryUrl() string {
	if x != nil {
		return x.EntryUrl
	}
	return ""
}

func (x *Event_SessionContext) GetReferrers() []string {
	if x != nil {
		return x.Referrers
	}
	return nil
}

func (x *Event_SessionContext) GetSessionData() map[string]string {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *Event_SessionContext) GetNavigation() *Event_SessionContext_Navigation {
	if x != nil {
		return x.Navigation
	}
	return nil
}

type Event_TracingContext struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	TraceId       string                                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ServiceName   string                                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                                 `protobuf:"bytes,5,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	StartTime     int64                                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	DurationNs    int64                                  `protobuf:"varint,7,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Tags          map[string]string                      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   []*Event_TracingContext_SpanAnnotation `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_TracingContext) Reset() {
	*x = Event_TracingContext{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_TracingContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_TracingContext) ProtoMessage() {}

func (x *Event_TracingContext) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_TracingContext.ProtoReflect.Descriptor instead.
func (*Event_TracingContext) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Event_TracingContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Event_TracingContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Event_TracingContext) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Event_TracingContext) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Event_TracingContext) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Event_TracingContext) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Event_TracingContext) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *Event_TracingContext) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event_TracingContext) GetAnnotations() []*Event_TracingContext_SpanAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Event_Payload struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	EventType     string                       `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	RawData       []byte                       `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	JsonBlob      string                       `protobuf:"bytes,3,opt,name=json_blob,json=jsonBlob,proto3" json:"json_blob,omitempty"`
	Metadata      map[string]string            `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CustomFields  []*Event_Payload_CustomField `protobuf:"bytes,5,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Payload) Reset() {
	*x = Event_Payload{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Payload) ProtoMessage() {}

func (x *Event_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Payload.ProtoReflect.Descriptor instead.
func (*Event_Payload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Event_Payload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event_Payload) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *Event_Payload) GetJsonBlob() string {
	if x != nil {
		return x.JsonBlob
	}
	return ""
}

func (x *Event_Payload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event_Payload) GetCustomFields() []*Event_Payload_CustomField {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

type Event_Enrichment struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Geo           *Event_Enrichment_Geolocation    `protobuf:"bytes,1,opt,name=geo,proto3" json:"geo,omitempty"`
	Ua            *Event_Enrichment_UserAgentInfo  `protobuf:"bytes,2,opt,name=ua,proto3" json:"ua,omitempty"`
	Device        *Event_Enrichment_DeviceInfo     `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Server        *Event_Enrichment_ServerInfo     `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	AbTest        *Event_Enrichment_ABTest         `protobuf:"bytes,5,opt,name=ab_test,json=abTest,proto3" json:"ab_test,omitempty"`
	Fraud         *Event_Enrichment_FraudDetection `protobuf:"bytes,6,opt,name=fraud,proto3" json:"fraud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Enrichment) Reset() {
	*x = Event_Enrichment{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment) ProtoMessage() {}

func (x *Event_Enrichment) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment.ProtoReflect.Descriptor instead.
func (*Event_Enrichment) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Event_Enrichment) GetGeo() *Event_Enrichment_Geolocation {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Event_Enrichment) GetUa() *Event_Enrichment_UserAgentInfo {
	if x != nil {
		return x.Ua
	}
	return nil
}

func (x *Event_Enrichment) GetDevice() *Event_Enrichment_DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *Event_Enrichment) GetServer() *Event_Enrichment_ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Event_Enrichment) GetAbTest() *Event_Enrichment_ABTest {
	if x != nil {
		return x.AbTest
	}
	return nil
}

func (x *Event_Enrichment) GetFraud() *Event_Enrichment_FraudDetection {
	if x != nil {
		return x.Fraud
	}
	return nil
}

type Event_Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Metric) Reset() {
	*x = Event_Metric{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Metric) ProtoMessage() {}

func (x *Event_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Metric.ProtoReflect.Descriptor instead.
func (*Event_Metric) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Event_Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event_Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Event_Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Event_Metric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event_Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Event_Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Tag) Reset() {
	*x = Event_Tag{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Tag) ProtoMessage() {}

func (x *Event_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Tag.ProtoReflect.Descriptor instead.
func (*Event_Tag) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Event_Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Event_Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Event_UserContext_Profile struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Email         string                             `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                             `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []string                           `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Preferences   map[string]string                  `protobuf:"bytes,4,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Account       *Event_UserContext_Profile_Account `protobuf:"bytes,10,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_UserContext_Profile) Reset() {
	*x = Event_UserContext_Profile{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_UserContext_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UserContext_Profile) ProtoMessage() {}

func (x *Event_UserContext_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UserContext_Profile.ProtoReflect.Descriptor instead.
func (*Event_UserContext_Profile) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Event_UserContext_Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Event_UserContext_Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Event_UserContext_Profile) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Event_UserContext_Profile) GetPreferences() map[string]string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *Event_UserContext_Profile) GetAccount() *Event_UserContext_Profile_Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type Event_UserContext_Profile_Account struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	AccountId     string                                     `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Tier          string                                     `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	CreatedAt     int64                                      `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Permissions   []string                                   `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Metadata      map[string]string                          `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Billing       *Event_UserContext_Profile_Account_Billing `protobuf:"bytes,10,opt,name=billing,proto3" json:"billing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_UserContext_Profile_Account) Reset() {
	*x = Event_UserContext_Profile_Account{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_UserContext_Profile_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UserContext_Profile_Account) ProtoMessage() {}

func (x *Event_UserContext_Profile_Account) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UserContext_Profile_Account.ProtoReflect.Descriptor instead.
func (*Event_UserContext_Profile_Account) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0, 1, 1}
}

func (x *Event_UserContext_Profile_Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Event_UserContext_Profile_Account) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Event_UserContext_Profile_Account) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event_UserContext_Profile_Account) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Event_UserContext_Profile_Account) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event_UserContext_Profile_Account) GetBilling() *Event_UserContext_Profile_Account_Billing {
	if x != nil {
		return x.Billing
	}
	return nil
}

type Event_UserContext_Profile_Account_Billing struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	PaymentMethod string                                               `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Currency      string                                               `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Invoices      []*Event_UserContext_Profile_Account_Billing_Invoice `protobuf:"bytes,3,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_UserContext_Profile_Account_Billing) Reset() {
	*x = Event_UserContext_Profile_Account_Billing{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_UserContext_Profile_Account_Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UserContext_Profile_Account_Billing) ProtoMessage() {}

func (x *Event_UserContext_Profile_Account_Billing) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UserContext_Profile_Account_Billing.ProtoReflect.Descriptor instead.
func (*Event_UserContext_Profile_Account_Billing) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0, 1, 1, 1}
}

func (x *Event_UserContext_Profile_Account_Billing) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Event_UserContext_Profile_Account_Billing) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Event_UserContext_Profile_Account_Billing) GetInvoices() []*Event_UserContext_Profile_Account_Billing_Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type Event_UserContext_Profile_Account_Billing_Invoice struct {
	state         protoimpl.MessageState                                        `protogen:"open.v1"`
	InvoiceId     string                                                        `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Amount        int64                                                         `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                                                        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Items         []*Event_UserContext_Profile_Account_Billing_Invoice_LineItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) Reset() {
	*x = Event_UserContext_Profile_Account_Billing_Invoice{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UserContext_Profile_Account_Billing_Invoice) ProtoMessage() {}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UserContext_Profile_Account_Billing_Invoice.ProtoReflect.Descriptor instead.
func (*Event_UserContext_Profile_Account_Billing_Invoice) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0, 1, 1, 1, 0}
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice) GetItems() []*Event_UserContext_Profile_Account_Billing_Invoice_LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type Event_UserContext_Profile_Account_Billing_Invoice_LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) Reset() {
	*x = Event_UserContext_Profile_Account_Billing_Invoice_LineItem{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_UserContext_Profile_Account_Billing_Invoice_LineItem) ProtoMessage() {}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_UserContext_Profile_Account_Billing_Invoice_LineItem.ProtoReflect.Descriptor instead.
func (*Event_UserContext_Profile_Account_Billing_Invoice_LineItem) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0, 1, 1, 1, 0, 0}
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Event_UserContext_Profile_Account_Billing_Invoice_LineItem) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type Event_SessionContext_Navigation struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	PageViews     []*Event_SessionContext_Navigation_PageView   `protobuf:"bytes,1,rep,name=page_views,json=pageViews,proto3" json:"page_views,omitempty"`
	Clicks        []*Event_SessionContext_Navigation_ClickEvent `protobuf:"bytes,2,rep,name=clicks,proto3" json:"clicks,omitempty"`
	Errors        []*Event_SessionContext_Navigation_ErrorEvent `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_SessionContext_Navigation) Reset() {
	*x = Event_SessionContext_Navigation{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_SessionContext_Navigation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_SessionContext_Navigation) ProtoMessage() {}

func (x *Event_SessionContext_Navigation) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_SessionContext_Navigation.ProtoReflect.Descriptor instead.
func (*Event_SessionContext_Navigation) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Event_SessionContext_Navigation) GetPageViews() []*Event_SessionContext_Navigation_PageView {
	if x != nil {
		return x.PageViews
	}
	return nil
}

func (x *Event_SessionContext_Navigation) GetClicks() []*Event_SessionContext_Navigation_ClickEvent {
	if x != nil {
		return x.Clicks
	}
	return nil
}

func (x *Event_SessionContext_Navigation) GetErrors() []*Event_SessionContext_Navigation_ErrorEvent {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Event_SessionContext_Navigation_PageView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Referrer      string                 `protobuf:"bytes,5,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_SessionContext_Navigation_PageView) Reset() {
	*x = Event_SessionContext_Navigation_PageView{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_SessionContext_Navigation_PageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_SessionContext_Navigation_PageView) ProtoMessage() {}

func (x *Event_SessionContext_Navigation_PageView) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_SessionContext_Navigation_PageView.ProtoReflect.Descriptor instead.
func (*Event_SessionContext_Navigation_PageView) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *Event_SessionContext_Navigation_PageView) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Event_SessionContext_Navigation_PageView) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event_SessionContext_Navigation_PageView) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event_SessionContext_Navigation_PageView) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Event_SessionContext_Navigation_PageView) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *Event_SessionContext_Navigation_PageView) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type Event_SessionContext_Navigation_ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementId     string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	ElementType   string                 `protobuf:"bytes,2,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	Xpath         string                 `protobuf:"bytes,3,opt,name=xpath,proto3" json:"xpath,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_SessionContext_Navigation_ClickEvent) Reset() {
	*x = Event_SessionContext_Navigation_ClickEvent{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_SessionContext_Navigation_ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_SessionContext_Navigation_ClickEvent) ProtoMessage() {}

func (x *Event_SessionContext_Navigation_ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_SessionContext_Navigation_ClickEvent.ProtoReflect.Descriptor instead.
func (*Event_SessionContext_Navigation_ClickEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 1, 1, 1}
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetElementType() string {
	if x != nil {
		return x.ElementType
	}
	return ""
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetXpath() string {
	if x != nil {
		return x.Xpath
	}
	return ""
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event_SessionContext_Navigation_ClickEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type Event_SessionContext_Navigation_ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorType     string                 `protobuf:"bytes,1,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace    string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_SessionContext_Navigation_ErrorEvent) Reset() {
	*x = Event_SessionContext_Navigation_ErrorEvent{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_SessionContext_Navigation_ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_SessionContext_Navigation_ErrorEvent) ProtoMessage() {}

func (x *Event_SessionContext_Navigation_ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_SessionContext_Navigation_ErrorEvent.ProtoReflect.Descriptor instead.
func (*Event_SessionContext_Navigation_ErrorEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 1, 1, 2}
}

func (x *Event_SessionContext_Navigation_ErrorEvent) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *Event_SessionContext_Navigation_ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event_SessionContext_Navigation_ErrorEvent) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *Event_SessionContext_Navigation_ErrorEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event_SessionContext_Navigation_ErrorEvent) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type Event_TracingContext_SpanAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_TracingContext_SpanAnnotation) Reset() {
	*x = Event_TracingContext_SpanAnnotation{}
	mi := &file_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_TracingContext_SpanAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_TracingContext_SpanAnnotation) ProtoMessage() {}

func (x *Event_TracingContext_SpanAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_TracingContext_SpanAnnotation.ProtoReflect.Descriptor instead.
func (*Event_TracingContext_SpanAnnotation) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Event_TracingContext_SpanAnnotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Event_TracingContext_SpanAnnotation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Event_TracingContext_SpanAnnotation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Event_Payload_CustomField struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Name          string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          Event_Payload_CustomField_FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=arrowflow.Event_Payload_CustomField_FieldType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Payload_CustomField) Reset() {
	*x = Event_Payload_CustomField{}
	mi := &file_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Payload_CustomField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Payload_CustomField) ProtoMessage() {}

func (x *Event_Payload_CustomField) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Payload_CustomField.ProtoReflect.Descriptor instead.
func (*Event_Payload_CustomField) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *Event_Payload_CustomField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event_Payload_CustomField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Event_Payload_CustomField) GetType() Event_Payload_CustomField_FieldType {
	if x != nil {
		return x.Type
	}
	return Event_Payload_CustomField_STRING
}

type Event_Enrichment_Geolocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Isp           string                 `protobuf:"bytes,7,opt,name=isp,proto3" json:"isp,omitempty"`
	Asn           string                 `protobuf:"bytes,8,opt,name=asn,proto3" json:"asn,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,9,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Enrichment_Geolocation) Reset() {
	*x = Event_Enrichment_Geolocation{}
	mi := &file_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment_Geolocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment_Geolocation) ProtoMessage() {}

func (x *Event_Enrichment_Geolocation) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment_Geolocation.ProtoReflect.Descriptor instead.
func (*Event_Enrichment_Geolocation) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Event_Enrichment_Geolocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Event_Enrichment_Geolocation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Event_Enrichment_Geolocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Event_Enrichment_Geolocation) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Event_Enrichment_Geolocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Event_Enrichment_Geolocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Event_Enrichment_Geolocation) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *Event_Enrichment_Geolocation) GetAsn() string {
	if x != nil {
		return x.Asn
	}
	return ""
}

func (x *Event_Enrichment_Geolocation) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Event_Enrichment_UserAgentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Browser        string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion string                 `protobuf:"bytes,2,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion      string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceType     string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceBrand    string                 `protobuf:"bytes,6,opt,name=device_brand,json=deviceBrand,proto3" json:"device_brand,omitempty"`
	DeviceModel    string                 `protobuf:"bytes,7,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	IsMobile       bool                   `protobuf:"varint,8,opt,name=is_mobile,json=isMobile,proto3" json:"is_mobile,omitempty"`
	IsBot          bool                   `protobuf:"varint,9,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	RawHeaders     map[string]string      `protobuf:"bytes,10,rep,name=raw_headers,json=rawHeaders,proto3" json:"raw_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event_Enrichment_UserAgentInfo) Reset() {
	*x = Event_Enrichment_UserAgentInfo{}
	mi := &file_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment_UserAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment_UserAgentInfo) ProtoMessage() {}

func (x *Event_Enrichment_UserAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment_UserAgentInfo.ProtoReflect.Descriptor instead.
func (*Event_Enrichment_UserAgentInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4, 1}
}

func (x *Event_Enrichment_UserAgentInfo) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetDeviceBrand() string {
	if x != nil {
		return x.DeviceBrand
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *Event_Enrichment_UserAgentInfo) GetIsMobile() bool {
	if x != nil {
		return x.IsMobile
	}
	return false
}

func (x *Event_Enrichment_UserAgentInfo) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *Event_Enrichment_UserAgentInfo) GetRawHeaders() map[string]string {
	if x != nil {
		return x.RawHeaders
	}
	return nil
}

type Event_Enrichment_DeviceInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceType       string                 `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Os               string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion        string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	ScreenResolution string                 `protobuf:"bytes,5,opt,name=screen_resolution,json=screenResolution,proto3" json:"screen_resolution,omitempty"`
	ScreenWidth      int32                  `protobuf:"varint,6,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight     int32                  `protobuf:"varint,7,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	ColorDepth       int32                  `protobuf:"varint,8,opt,name=color_depth,json=colorDepth,proto3" json:"color_depth,omitempty"`
	IsTablet         bool                   `protobuf:"varint,9,opt,name=is_tablet,json=isTablet,proto3" json:"is_tablet,omitempty"`
	IsMobile         bool                   `protobuf:"varint,10,opt,name=is_mobile,json=isMobile,proto3" json:"is_mobile,omitempty"`
	Capabilities     map[string]string      `protobuf:"bytes,11,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event_Enrichment_DeviceInfo) Reset() {
	*x = Event_Enrichment_DeviceInfo{}
	mi := &file_event_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment_DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment_DeviceInfo) ProtoMessage() {}

func (x *Event_Enrichment_DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment_DeviceInfo.ProtoReflect.Descriptor instead.
func (*Event_Enrichment_DeviceInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4, 2}
}

func (x *Event_Enrichment_DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Event_Enrichment_DeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Event_Enrichment_DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Event_Enrichment_DeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Event_Enrichment_DeviceInfo) GetScreenResolution() string {
	if x != nil {
		return x.ScreenResolution
	}
	return ""
}

func (x *Event_Enrichment_DeviceInfo) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *Event_Enrichment_DeviceInfo) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *Event_Enrichment_DeviceInfo) GetColorDepth() int32 {
	if x != nil {
		return x.ColorDepth
	}
	return 0
}

func (x *Event_Enrichment_DeviceInfo) GetIsTablet() bool {
	if x != nil {
		return x.IsTablet
	}
	return false
}

func (x *Event_Enrichment_DeviceInfo) GetIsMobile() bool {
	if x != nil {
		return x.IsMobile
	}
	return false
}

func (x *Event_Enrichment_DeviceInfo) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Event_Enrichment_ServerInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerName        string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Datacenter        string                 `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Region            string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Cluster           string                 `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Tags              map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AvailableServices []string               `protobuf:"bytes,6,rep,name=available_services,json=availableServices,proto3" json:"available_services,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event_Enrichment_ServerInfo) Reset() {
	*x = Event_Enrichment_ServerInfo{}
	mi := &file_event_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment_ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment_ServerInfo) ProtoMessage() {}

func (x *Event_Enrichment_ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment_ServerInfo.ProtoReflect.Descriptor instead.
func (*Event_Enrichment_ServerInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4, 3}
}

func (x *Event_Enrichment_ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Event_Enrichment_ServerInfo) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *Event_Enrichment_ServerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Event_Enrichment_ServerInfo) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Event_Enrichment_ServerInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event_Enrichment_ServerInfo) GetAvailableServices() []string {
	if x != nil {
		return x.AvailableServices
	}
	return nil
}

type Event_Enrichment_ABTest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExperimentId      string                 `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	VariantId         string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	ExperimentName    string                 `protobuf:"bytes,3,opt,name=experiment_name,json=experimentName,proto3" json:"experiment_name,omitempty"`
	VariantName       string                 `protobuf:"bytes,4,opt,name=variant_name,json=variantName,proto3" json:"variant_name,omitempty"`
	TrafficAllocation float64                `protobuf:"fixed64,5,opt,name=traffic_allocation,json=trafficAllocation,proto3" json:"traffic_allocation,omitempty"`
	Parameters        map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event_Enrichment_ABTest) Reset() {
	*x = Event_Enrichment_ABTest{}
	mi := &file_event_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment_ABTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment_ABTest) ProtoMessage() {}

func (x *Event_Enrichment_ABTest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment_ABTest.ProtoReflect.Descriptor instead.
func (*Event_Enrichment_ABTest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4, 4}
}

func (x *Event_Enrichment_ABTest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *Event_Enrichment_ABTest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *Event_Enrichment_ABTest) GetExperimentName() string {
	if x != nil {
		return x.ExperimentName
	}
	return ""
}

func (x *Event_Enrichment_ABTest) GetVariantName() string {
	if x != nil {
		return x.VariantName
	}
	return ""
}

func (x *Event_Enrichment_ABTest) GetTrafficAllocation() float64 {
	if x != nil {
		return x.TrafficAllocation
	}
	return 0
}

func (x *Event_Enrichment_ABTest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Event_Enrichment_FraudDetection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiskScore     int32                  `protobuf:"varint,1,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RiskLevel     string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Flags         []string               `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	Signals       map[string]string      `protobuf:"bytes,4,rep,name=signals,proto3" json:"signals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Enrichment_FraudDetection) Reset() {
	*x = Event_Enrichment_FraudDetection{}
	mi := &file_event_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Enrichment_FraudDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Enrichment_FraudDetection) ProtoMessage() {}

func (x *Event_Enrichment_FraudDetection) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Enrichment_FraudDetection.ProtoReflect.Descriptor instead.
func (*Event_Enrichment_FraudDetection) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 4, 5}
}

func (x *Event_Enrichment_FraudDetection) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *Event_Enrichment_FraudDetection) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *Event_Enrichment_FraudDetection) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Event_Enrichment_FraudDetection) GetSignals() map[string]string {
	if x != nil {
		return x.Signals
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\tarrowflow\"\xd69\n" +
	"\x05Event\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12'\n" +
	"\x0fevent_timestamp\x18\x02 \x01(\x03R\x0eeventTimestamp\x120\n" +
	"\x04user\x18\n" +
	" \x01(\v2\x1c.arrowflow.Event.UserContextR\x04user\x129\n" +
	"\asession\x18\v \x01(\v2\x1f.arrowflow.Event.SessionContextR\asession\x129\n" +
	"\atracing\x18\f \x01(\v2\x1f.arrowflow.Event.TracingContextR\atracing\x122\n" +
	"\apayload\x18\x14 \x01(\v2\x18.arrowflow.Event.PayloadR\apayload\x12;\n" +
	"\n" +
	"enrichment\x18\x15 \x01(\v2\x1b.arrowflow.Event.EnrichmentR\n" +
	"enrichment\x121\n" +
	"\ametrics\x18\x1e \x03(\v2\x17.arrowflow.Event.MetricR\ametrics\x12(\n" +
	"\x04tags\x18\x1f \x03(\v2\x14.arrowflow.Event.TagR\x04tags\x1a\xe3\v\n" +
	"\vUserContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12L\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2,.arrowflow.Event.UserContext.AttributesEntryR\n" +
	"attributes\x12>\n" +
	"\aprofile\x18\n" +
	" \x01(\v2$.arrowflow.Event.UserContext.ProfileR\aprofile\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xf3\b\n" +
	"\aProfile\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12W\n" +
	"\vpreferences\x18\x04 \x03(\v25.arrowflow.Event.UserContext.Profile.PreferencesEntryR\vpreferences\x12F\n" +
	"\aaccount\x18\n" +
	" \x01(\v2,.arrowflow.Event.UserContext.Profile.AccountR\aaccount\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xbe\x06\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12V\n" +
	"\bmetadata\x18\x05 \x03(\v2:.arrowflow.Event.UserContext.Profile.Account.MetadataEntryR\bmetadata\x12N\n" +
	"\abilling\x18\n" +
	" \x01(\v24.arrowflow.Event.UserContext.Profile.Account.BillingR\abilling\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xd9\x03\n" +
	"\aBilling\x12%\n" +
	"\x0epayment_method\x18\x01 \x01(\tR\rpaymentMethod\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12X\n" +
	"\binvoices\x18\x03 \x03(\v2<.arrowflow.Event.UserContext.Profile.Account.Billing.InvoiceR\binvoices\x1a\xb0\x02\n" +
	"\aInvoice\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12[\n" +
	"\x05items\x18\x04 \x03(\v2E.arrowflow.Event.UserContext.Profile.Account.Billing.Invoice.LineItemR\x05items\x1ay\n" +
	"\bLineItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x03R\tunitPrice\x1a\x84\f\n" +
	"\x0eSessionContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\x03R\tstartedAt\x12#\n" +
	"\rlast_activity\x18\x03 \x01(\x03R\flastActivity\x12\x1b\n" +
	"\tentry_url\x18\x04 \x01(\tR\bentryUrl\x12\x1c\n" +
	"\treferrers\x18\x05 \x03(\tR\treferrers\x12S\n" +
	"\fsession_data\x18\x06 \x03(\v20.arrowflow.Event.SessionContext.SessionDataEntryR\vsessionData\x12J\n" +
	"\n" +
	"navigation\x18\n" +
	" \x01(\v2*.arrowflow.Event.SessionContext.NavigationR\n" +
	"navigation\x1a>\n" +
	"\x10SessionDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xf2\b\n" +
	"\n" +
	"Navigation\x12R\n" +
	"\n" +
	"page_views\x18\x01 \x03(\v23.arrowflow.Event.SessionContext.Navigation.PageViewR\tpageViews\x12M\n" +
	"\x06clicks\x18\x02 \x03(\v25.arrowflow.Event.SessionContext.Navigation.ClickEventR\x06clicks\x12M\n" +
	"\x06errors\x18\x03 \x03(\v25.arrowflow.Event.SessionContext.Navigation.ErrorEventR\x06errors\x1a\xa1\x02\n" +
	"\bPageView\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x12\x1a\n" +
	"\breferrer\x18\x05 \x01(\tR\breferrer\x12W\n" +
	"\x06params\x18\x06 \x03(\v2?.arrowflow.Event.SessionContext.Navigation.PageView.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xac\x02\n" +
	"\n" +
	"ClickEvent\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12!\n" +
	"\felement_type\x18\x02 \x01(\tR\velementType\x12\x14\n" +
	"\x05xpath\x18\x03 \x01(\tR\x05xpath\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12S\n" +
	"\x04data\x18\a \x03(\v2?.arrowflow.Event.SessionContext.Navigation.ClickEvent.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\x9e\x02\n" +
	"\n" +
	"ErrorEvent\x12\x1d\n" +
	"\n" +
	"error_type\x18\x01 \x01(\tR\terrorType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\\\n" +
	"\acontext\x18\x05 \x03(\v2B.arrowflow.Event.SessionContext.Navigation.ErrorEvent.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\x96\x04\n" +
	"\x0eTracingContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x05 \x01(\tR\roperationName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vduration_ns\x18\a \x01(\x03R\n" +
	"durationNs\x12=\n" +
	"\x04tags\x18\b \x03(\v2).arrowflow.Event.TracingContext.TagsEntryR\x04tags\x12P\n" +
	"\vannotations\x18\t \x03(\v2..arrowflow.Event.TracingContext.SpanAnnotationR\vannotations\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aV\n" +
	"\x0eSpanAnnotation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a\xf2\x03\n" +
	"\aPayload\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\fR\arawData\x12\x1b\n" +
	"\tjson_blob\x18\x03 \x01(\tR\bjsonBlob\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.arrowflow.Event.Payload.MetadataEntryR\bmetadata\x12I\n" +
	"\rcustom_fields\x18\x05 \x03(\v2$.arrowflow.Event.Payload.CustomFieldR\fcustomFields\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xc3\x01\n" +
	"\vCustomField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12B\n" +
	"\x04type\x18\x03 \x01(\x0e2..arrowflow.Event.Payload.CustomField.FieldTypeR\x04type\"F\n" +
	"\tFieldType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x01\x12\v\n" +
	"\aBOOLEAN\x10\x02\x12\b\n" +
	"\x04JSON\x10\x03\x12\n" +
	"\n" +
	"\x06BINARY\x10\x04\x1a\xfd\x13\n" +
	"\n" +
	"Enrichment\x129\n" +
	"\x03geo\x18\x01 \x01(\v2'.arrowflow.Event.Enrichment.GeolocationR\x03geo\x129\n" +
	"\x02ua\x18\x02 \x01(\v2).arrowflow.Event.Enrichment.UserAgentInfoR\x02ua\x12>\n" +
	"\x06device\x18\x03 \x01(\v2&.arrowflow.Event.Enrichment.DeviceInfoR\x06device\x12>\n" +
	"\x06server\x18\x04 \x01(\v2&.arrowflow.Event.Enrichment.ServerInfoR\x06server\x12;\n" +
	"\aab_test\x18\x05 \x01(\v2\".arrowflow.Event.Enrichment.ABTestR\x06abTest\x12@\n" +
	"\x05fraud\x18\x06 \x01(\v2*.arrowflow.Event.Enrichment.FraudDetectionR\x05fraud\x1a\xd1\x02\n" +
	"\vGeolocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x10\n" +
	"\x03isp\x18\a \x01(\tR\x03isp\x12\x10\n" +
	"\x03asn\x18\b \x01(\tR\x03asn\x12H\n" +
	"\x05extra\x18\t \x03(\v22.arrowflow.Event.Enrichment.Geolocation.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xb7\x03\n" +
	"\rUserAgentInfo\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\x02 \x01(\tR\x0ebrowserVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12!\n" +
	"\fdevice_brand\x18\x06 \x01(\tR\vdeviceBrand\x12!\n" +
	"\fdevice_model\x18\a \x01(\tR\vdeviceModel\x12\x1b\n" +
	"\tis_mobile\x18\b \x01(\bR\bisMobile\x12\x15\n" +
	"\x06is_bot\x18\t \x01(\bR\x05isBot\x12Z\n" +
	"\vraw_headers\x18\n" +
	" \x03(\v29.arrowflow.Event.Enrichment.UserAgentInfo.RawHeadersEntryR\n" +
	"rawHeaders\x1a=\n" +
	"\x0fRawHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xe8\x03\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12+\n" +
	"\x11screen_resolution\x18\x05 \x01(\tR\x10screenResolution\x12!\n" +
	"\fscreen_width\x18\x06 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\a \x01(\x05R\fscreenHeight\x12\x1f\n" +
	"\vcolor_depth\x18\b \x01(\x05R\n" +
	"colorDepth\x12\x1b\n" +
	"\tis_tablet\x18\t \x01(\bR\bisTablet\x12\x1b\n" +
	"\tis_mobile\x18\n" +
	" \x01(\bR\bisMobile\x12\\\n" +
	"\fcapabilities\x18\v \x03(\v28.arrowflow.Event.Enrichment.DeviceInfo.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xad\x02\n" +
	"\n" +
	"ServerInfo\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x02 \x01(\tR\n" +
	"datacenter\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x12D\n" +
	"\x04tags\x18\x05 \x03(\v20.arrowflow.Event.Enrichment.ServerInfo.TagsEntryR\x04tags\x12-\n" +
	"\x12available_services\x18\x06 \x03(\tR\x11availableServices\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xda\x02\n" +
	"\x06ABTest\x12#\n" +
	"\rexperiment_id\x18\x01 \x01(\tR\fexperimentId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12'\n" +
	"\x0fexperiment_name\x18\x03 \x01(\tR\x0eexperimentName\x12!\n" +
	"\fvariant_name\x18\x04 \x01(\tR\vvariantName\x12-\n" +
	"\x12traffic_allocation\x18\x05 \x01(\x01R\x11trafficAllocation\x12R\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v22.arrowflow.Event.Enrichment.ABTest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xf3\x01\n" +
	"\x0eFraudDetection\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x01 \x01(\x05R\triskScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\x12Q\n" +
	"\asignals\x18\x04 \x03(\v27.arrowflow.Event.Enrichment.FraudDetection.SignalsEntryR\asignals\x1a:\n" +
	"\fSignalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xdc\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12;\n" +
	"\x06labels\x18\x05 \x03(\v2#.arrowflow.Event.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB/Z-github.com/TFMV/arrowflow/internal/schemas/pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_event_proto_goTypes = []any{
	(Event_Payload_CustomField_FieldType)(0),  // 0: arrowflow.Event.Payload.CustomField.FieldType
	(*Event)(nil),                             // 1: arrowflow.Event
	(*Event_UserContext)(nil),                 // 2: arrowflow.Event.UserContext
	(*Event_SessionContext)(nil),              // 3: arrowflow.Event.SessionContext
	(*Event_TracingContext)(nil),              // 4: arrowflow.Event.TracingContext
	(*Event_Payload)(nil),                     // 5: arrowflow.Event.Payload
	(*Event_Enrichment)(nil),                  // 6: arrowflow.Event.Enrichment
	(*Event_Metric)(nil),                      // 7: arrowflow.Event.Metric
	(*Event_Tag)(nil),                         // 8: arrowflow.Event.Tag
	nil,                                       // 9: arrowflow.Event.UserContext.AttributesEntry
	(*Event_UserContext_Profile)(nil),         // 10: arrowflow.Event.UserContext.Profile
	nil,                                       // 11: arrowflow.Event.UserContext.Profile.PreferencesEntry
	(*Event_UserContext_Profile_Account)(nil), // 12: arrowflow.Event.UserContext.Profile.Account
	nil, // 13: arrowflow.Event.UserContext.Profile.Account.MetadataEntry
	(*Event_UserContext_Profile_Account_Billing)(nil),                  // 14: arrowflow.Event.UserContext.Profile.Account.Billing
	(*Event_UserContext_Profile_Account_Billing_Invoice)(nil),          // 15: arrowflow.Event.UserContext.Profile.Account.Billing.Invoice
	(*Event_UserContext_Profile_Account_Billing_Invoice_LineItem)(nil), // 16: arrowflow.Event.UserContext.Profile.Account.Billing.Invoice.LineItem
	nil,                                     // 17: arrowflow.Event.SessionContext.SessionDataEntry
	(*Event_SessionContext_Navigation)(nil), // 18: arrowflow.Event.SessionContext.Navigation
	(*Event_SessionContext_Navigation_PageView)(nil),   // 19: arrowflow.Event.SessionContext.Navigation.PageView
	(*Event_SessionContext_Navigation_ClickEvent)(nil), // 20: arrowflow.Event.SessionContext.Navigation.ClickEvent
	(*Event_SessionContext_Navigation_ErrorEvent)(nil), // 21: arrowflow.Event.SessionContext.Navigation.ErrorEvent
	nil, // 22: arrowflow.Event.SessionContext.Navigation.PageView.ParamsEntry
	nil, // 23: arrowflow.Event.SessionContext.Navigation.ClickEvent.DataEntry
	nil, // 24: arrowflow.Event.SessionContext.Navigation.ErrorEvent.ContextEntry
	nil, // 25: arrowflow.Event.TracingContext.TagsEntry
	(*Event_TracingContext_SpanAnnotation)(nil), // 26: arrowflow.Event.TracingContext.SpanAnnotation
	nil,                                     // 27: arrowflow.Event.Payload.MetadataEntry
	(*Event_Payload_CustomField)(nil),       // 28: arrowflow.Event.Payload.CustomField
	(*Event_Enrichment_Geolocation)(nil),    // 29: arrowflow.Event.Enrichment.Geolocation
	(*Event_Enrichment_UserAgentInfo)(nil),  // 30: arrowflow.Event.Enrichment.UserAgentInfo
	(*Event_Enrichment_DeviceInfo)(nil),     // 31: arrowflow.Event.Enrichment.DeviceInfo
	(*Event_Enrichment_ServerInfo)(nil),     // 32: arrowflow.Event.Enrichment.ServerInfo
	(*Event_Enrichment_ABTest)(nil),         // 33: arrowflow.Event.Enrichment.ABTest
	(*Event_Enrichment_FraudDetection)(nil), // 34: arrowflow.Event.Enrichment.FraudDetection
	nil,                                     // 35: arrowflow.Event.Enrichment.Geolocation.ExtraEntry
	nil,                                     // 36: arrowflow.Event.Enrichment.UserAgentInfo.RawHeadersEntry
	nil,                                     // 37: arrowflow.Event.Enrichment.DeviceInfo.CapabilitiesEntry
	nil,                                     // 38: arrowflow.Event.Enrichment.ServerInfo.TagsEntry
	nil,                                     // 39: arrowflow.Event.Enrichment.ABTest.ParametersEntry
	nil,                                     // 40: arrowflow.Event.Enrichment.FraudDetection.SignalsEntry
	nil,                                     // 41: arrowflow.Event.Metric.LabelsEntry
}
var file_event_proto_depIdxs = []int32{
	2,  // 0: arrowflow.Event.user:type_name -> arrowflow.Event.UserContext
	3,  // 1: arrowflow.Event.session:type_name -> arrowflow.Event.SessionContext
	4,  // 2: arrowflow.Event.tracing:type_name -> arrowflow.Event.TracingContext
	5,  // 3: arrowflow.Event.payload:type_name -> arrowflow.Event.Payload
	6,  // 4: arrowflow.Event.enrichment:type_name -> arrowflow.Event.Enrichment
	7,  // 5: arrowflow.Event.metrics:type_name -> arrowflow.Event.Metric
	8,  // 6: arrowflow.Event.tags:type_name -> arrowflow.Event.Tag
	9,  // 7: arrowflow.Event.UserContext.attributes:type_name -> arrowflow.Event.UserContext.AttributesEntry
	10, // 8: arrowflow.Event.UserContext.profile:type_name -> arrowflow.Event.UserContext.Profile
	17, // 9: arrowflow.Event.SessionContext.session_data:type_name -> arrowflow.Event.SessionContext.SessionDataEntry
	18, // 10: arrowflow.Event.SessionContext.navigation:type_name -> arrowflow.Event.SessionContext.Navigation
	25, // 11: arrowflow.Event.TracingContext.tags:type_name -> arrowflow.Event.TracingContext.TagsEntry
	26, // 12: arrowflow.Event.TracingContext.annotations:type_name -> arrowflow.Event.TracingContext.SpanAnnotation
	27, // 13: arrowflow.Event.Payload.metadata:type_name -> arrowflow.Event.Payload.MetadataEntry
	28, // 14: arrowflow.Event.Payload.custom_fields:type_name -> arrowflow.Event.Payload.CustomField
	29, // 15: arrowflow.Event.Enrichment.geo:type_name -> arrowflow.Event.Enrichment.Geolocation
	30, // 16: arrowflow.Event.Enrichment.ua:type_name -> arrowflow.Event.Enrichment.UserAgentInfo
	31, // 17: arrowflow.Event.Enrichment.device:type_name -> arrowflow.Event.Enrichment.DeviceInfo
	32, // 18: arrowflow.Event.Enrichment.server:type_name -> arrowflow.Event.Enrichment.ServerInfo
	33, // 19: arrowflow.Event.Enrichment.ab_test:type_name -> arrowflow.Event.Enrichment.ABTest
	34, // 20: arrowflow.Event.Enrichment.fraud:type_name -> arrowflow.Event.Enrichment.FraudDetection
	41, // 21: arrowflow.Event.Metric.labels:type_name -> arrowflow.Event.Metric.LabelsEntry
	11, // 22: arrowflow.Event.UserContext.Profile.preferences:type_name -> arrowflow.Event.UserContext.Profile.PreferencesEntry
	12, // 23: arrowflow.Event.UserContext.Profile.account:type_name -> arrowflow.Event.UserContext.Profile.Account
	13, // 24: arrowflow.Event.UserContext.Profile.Account.metadata:type_name -> arrowflow.Event.UserContext.Profile.Account.MetadataEntry
	14, // 25: arrowflow.Event.UserContext.Profile.Account.billing:type_name -> arrowflow.Event.UserContext.Profile.Account.Billing
	15, // 26: arrowflow.Event.UserContext.Profile.Account.Billing.invoices:type_name -> arrowflow.Event.UserContext.Profile.Account.Billing.Invoice
	16, // 27: arrowflow.Event.UserContext.Profile.Account.Billing.Invoice.items:type_name -> arrowflow.Event.UserContext.Profile.Account.Billing.Invoice.LineItem
	19, // 28: arrowflow.Event.SessionContext.Navigation.page_views:type_name -> arrowflow.Event.SessionContext.Navigation.PageView
	20, // 29: arrowflow.Event.SessionContext.Navigation.clicks:type_name -> arrowflow.Event.SessionContext.Navigation.ClickEvent
	21, // 30: arrowflow.Event.SessionContext.Navigation.errors:type_name -> arrowflow.Event.SessionContext.Navigation.ErrorEvent
	22, // 31: arrowflow.Event.SessionContext.Navigation.PageView.params:type_name -> arrowflow.Event.SessionContext.Navigation.PageView.ParamsEntry
	23, // 32: arrowflow.Event.SessionContext.Navigation.ClickEvent.data:type_name -> arrowflow.Event.SessionContext.Navigation.ClickEvent.DataEntry
	24, // 33: arrowflow.Event.SessionContext.Navigation.ErrorEvent.context:type_name -> arrowflow.Event.SessionContext.Navigation.ErrorEvent.ContextEntry
	0,  // 34: arrowflow.Event.Payload.CustomField.type:type_name -> arrowflow.Event.Payload.CustomField.FieldType
	35, // 35: arrowflow.Event.Enrichment.Geolocation.extra:type_name -> arrowflow.Event.Enrichment.Geolocation.ExtraEntry
	36, // 36: arrowflow.Event.Enrichment.UserAgentInfo.raw_headers:type_name -> arrowflow.Event.Enrichment.UserAgentInfo.RawHeadersEntry
	37, // 37: arrowflow.Event.Enrichment.DeviceInfo.capabilities:type_name -> arrowflow.Event.Enrichment.DeviceInfo.CapabilitiesEntry
	38, // 38: arrowflow.Event.Enrichment.ServerInfo.tags:type_name -> arrowflow.Event.Enrichment.ServerInfo.TagsEntry
	39, // 39: arrowflow.Event.Enrichment.ABTest.parameters:type_name -> arrowflow.Event.Enrichment.ABTest.ParametersEntry
	40, // 40: arrowflow.Event.Enrichment.FraudDetection.signals:type_name -> arrowflow.Event.Enrichment.FraudDetection.SignalsEntry
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
